### ISSUE TITLE
Not on pypi?

### ISSUE THREAD

**Issue by ghost** [sandboxxapp/python-leanplum#9]
Hi!  What are your plans, if any, to upload this to Pypi at some point?

**Comment by epluntze** [comment]
Seeing as there is some interest I have added a story to our backlog to do that.  Hopefully we can slip it into our upcoming sprint but i can't promise anything.  I'll update this thread when we do though, Im glad someone is getting some utility from this!

**Comment by timlichen** [comment]
Heya @stugots,
Uploaded to: https://pypi.org/project/python-leanplum/0.6.0/
LMK if any issues arise.

**Comment by ghost** [comment]
Thank you!
